apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv-volume
  namespace: local
  labels:
    type: local
    release: stable
    environment: dev
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node
  claimRef:
    name: mssql-pvc
    namespace: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: 
    mssql-pv-volume
  matchLabels:
      release: "stable"
  matchExpressions:
    - {key: environment, operator: In, values: [dev]}