name: 'Terraform'

on: 
  push: 
    branches:
    - main
  # All pull requests
  pull_request:
    
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest 
    permissions:
      pull-requests: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
